### ISSUE TITLE
Semantic line breaks

### ISSUE THREAD

**Issue by sblom** [seriesseed/equity#2]
I don't know if the text will change much over time, but if you want meaningful diffs in the event of text changes, an idea that changed my life is [semantic line breaks](http://rhodesmill.org/brandon/2012/one-sentence-per-line/).

I worry that GitHub Flavored Markdown's literal interpretation of newlines might get in the way of that idea, though. :(

I see signs that @github wants to get better at handling document file types, though, so it's possible that GFM can be adapted to work for this. It would be so awesome to be able to use GitHub-style collaboration on legal documents!

**Comment by jboehmig** [comment]
That is a great link with a lot of application to legal docs, especially behind the scenes.  Thanks for passing along, Scott. 

I think your point about GFC interpretation of new lines is a valid point for this repo and my other initial worry would be that line breaking all the docs semantically would increase the overall length.  I'll leave this issue open for now in case anyone else wants to comment though.  It's a great concept regardless of whether it's implemented here or not, thanks for bringing it up.
