### ISSUE TITLE
Reg D

### ISSUE THREAD

**Issue by jrmiller82** [seriesseed/equity#22]
You'll need some sort of 'how to fill out the Reg D form' document. The securities' regulation aspect of these documents would make me a touch nervous to use.

**Comment by rickcolosimo** [comment]
Here's a link to a practice note on Reg D from Practical Law: http://us.practicallaw.com/8-382-6259

You can get to it through a free trial. (Disclosure: I work at Practical Law as a corporate and securities editor, but I didn't write this piece nor do I have a sales job.)

In general, though, I would consider the securities compliance stuff outside the scope of these documents: they include the relevant accredited investor representations, which is what you should expect to see.

**Comment by jrmiller82** [comment]
The penalties for the company are huge if the securities regs aren't followed exactly. 

Relying on 4(a)2 is unwise when complying with Reg D is so much easier. Not to mention state securities laws...

**Comment by goodcounsel** [comment]
I agree that securities law is important, but I don't see these as part of scope of these equity documents.

**Comment by jrmiller82** [comment]
You don't see compliance with potentially criminal violations of securities law as part of these documents? There's not even a sample PPM here!

**Comment by rickcolosimo** [comment]
No PPM is required when selling to accredited investors. If an offering requires a PPM, then it's unlikely to be a good fit for the solution presented by these documents. I see that solution as "a better alternative to widespread use of convertible notes without the headaches they bring." See the post at http://www.seriesseed.com/posts/2010/09/version-20-and-why-series-seed-documents-are-better-than-capped-convertible-notes.html for the recap.

**Comment by jrmiller82** [comment]
Many states require a similar disclosure document. You can't solely look at Reg D in a vacuum. There's a reason why a PPM is used quite often even when not required, even to private offerings solely to to accredited investors.
