### ISSUE TITLE
#310

### ISSUE THREAD

**Issue by amirziari** [seriesseed/equity#43]

**Comment by rickcolosimo** [comment]
Close

**Comment by rickcolosimo** [comment]
Close #43

**Comment by rickcolosimo** [comment]
Close #310

**Comment by amirziari** [comment]
من تا حالا موفق نشدم 1سنت از دارایی خود را کسب کنم لطفا  راحل ارائه کنید

**Comment by amirziari** [comment]
I have not succeeded in getting 1 cent of my assets yet. Please provide me a fortune
