### ISSUE TITLE
Section 500 of the California Corporations Code

### ISSUE THREAD

**Issue by thesmart** [seriesseed/equity#8]
California Corporations Code affects Delaware corporations?

```
In accordance with Section 500 of the California Corporations Code, a distribution can be made without regard to any preferential dividends arrears amount (as defined in Section 500 of the California Corporations Code)
```

https://github.com/seriesseed/equity/blob/master/Series%20Seed%20-%20Restated%20Certificate%20of%20Incorporation.md

**Comment by jboehmig** [comment]
Hi John, thanks reading through the docs and for your comment!  

You're actually zeroed in on a very complicated area of law, in my opinion, which is what laws apply to a corporation and when.  Judging by your top comment, I think you're interested in more of the general concepts, so you may want to check out something called the "internal affairs doctrine" (very general wikipedia overview here: https://en.wikipedia.org/wiki/Internal_affairs_doctrine).  

Generally speaking, a corporations internal affairs are governed by the laws of the state in which it is incorporated, but it is also subject to the laws of states where it is doing business, particularly with respect to actions it takes within that state.

I'm obviously not getting into the intricacies of the full issue here (both to save time and not bore you to death) but hopefully that gets at the issue that I think you were asking about.
